export const isLoggedIn = true;

export const userObj = {
  name: "hoon",
  profileImage:
    "https://firebasestorage.googleapis.com/v0/b/myplaylist-783c8.appspot.com/o/KakaoTalk_20210927_025101163.jpg?alt=media&token=4f3c0769-6a1b-40ee-a787-a4fd7e11487f",
};

export const PlaylistResponse = [
  {
    author: "hoon",
    bookmark: false,
    description: "우울할 때 듣는 플리",
    playlistId: 255486129307,
    songs: [
      {
        createdDate: "2022년 3월 13일",
        description: "기리보이의 찌질한 감성 노래",
        title: "기리보이 감성노래",
        videoId: "1sad12asxc",
      },
      {
        createdDate: "2022년 3월 11일",
        description: "기리보이의 하이텐션 노래",
        title: "기리보이 노래",
        videoId: "31dasdj2xc",
      },
      {
        createdDate: "2022년 3월 12일",
        description: "산책하며 듣는 기리보이 노래",
        title: "기리보이 산책",
        videoId: "kbamx9s2x1z",
      },
    ],
    title: "기리보이 플리",
    updatedDate: "2022년 3월 14일",
    visibility: true,
  },
  {
    author: "hoon",
    bookmark: false,
    description: "우울할 때 듣는 플리",
    playlistId: 1,
    songs: [
      {
        createdDate: "2022년 3월 13일",
        description: "기리보이의 찌질한 감성 노래",
        title: "기리보이 감성노래",
        videoId: "1sad12asxc",
      },
      {
        createdDate: "2022년 3월 11일",
        description: "기리보이의 하이텐션 노래",
        title: "기리보이 노래",
        videoId: "31dasdj2xc",
      },
      {
        createdDate: "2022년 3월 12일",
        description: "산책하며 듣는 기리보이 노래",
        title: "기리보이 산책",
        videoId: "kbamx9s2x1z",
      },
    ],
    title: "기리보이 플리",
    updatedDate: "2022년 3월 14일",
    visibility: true,
  },
  {
    author: "hoon",
    bookmark: false,
    description: "우울할 때 듣는 플리",
    playlistId: 2,
    songs: [
      {
        createdDate: "2022년 3월 13일",
        description: "기리보이의 찌질한 감성 노래",
        title: "기리보이 감성노래",
        videoId: "1sad12asxc",
      },
      {
        createdDate: "2022년 3월 11일",
        description: "기리보이의 하이텐션 노래",
        title: "기리보이 노래",
        videoId: "31dasdj2xc",
      },
      {
        createdDate: "2022년 3월 12일",
        description: "산책하며 듣는 기리보이 노래",
        title: "기리보이 산책",
        videoId: "kbamx9s2x1z",
      },
    ],
    title: "기리보이 플리",
    updatedDate: "2022년 3월 14일",
    visibility: true,
  },
  {
    author: "hoon",
    bookmark: false,
    description: "우울할 때 듣는 플리",
    playlistId: 3,
    songs: [
      {
        createdDate: "2022년 3월 13일",
        description: "기리보이의 찌질한 감성 노래",
        title: "기리보이 감성노래",
        videoId: "1sad12asxc",
      },
      {
        createdDate: "2022년 3월 11일",
        description: "기리보이의 하이텐션 노래",
        title: "기리보이 노래",
        videoId: "31dasdj2xc",
      },
      {
        createdDate: "2022년 3월 12일",
        description: "산책하며 듣는 기리보이 노래",
        title: "기리보이 산책",
        videoId: "kbamx9s2x1z",
      },
    ],
    title: "기리보이 플리",
    updatedDate: "2022년 3월 14일",
    visibility: true,
  },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 255486129307,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 1,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 3,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 255486129307,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 1,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
  // {
  //   author: "hoon",
  //   bookmark: false,
  //   description: "우울할 때 듣는 플리",
  //   playlistId: 2,
  //   songs: [
  //     {
  //       createdDate: "2022년 3월 13일",
  //       description: "기리보이의 찌질한 감성 노래",
  //       title: "기리보이 감성노래",
  //       videoId: "1sad12asxc",
  //     },
  //     {
  //       createdDate: "2022년 3월 11일",
  //       description: "기리보이의 하이텐션 노래",
  //       title: "기리보이 노래",
  //       videoId: "31dasdj2xc",
  //     },
  //     {
  //       createdDate: "2022년 3월 12일",
  //       description: "산책하며 듣는 기리보이 노래",
  //       title: "기리보이 산책",
  //       videoId: "kbamx9s2x1z",
  //     },
  //   ],
  //   title: "기리보이 플리",
  //   updatedDate: "2022년 3월 14일",
  //   visibility: true,
  // },
];
